# Generated by Django 2.0.3 on 2018-04-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Description')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation Date')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Case Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_authorisation', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Authorisation Status')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Authorisation')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='CaseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_classification', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Classification')),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Description')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation Date')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Case Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='CaseImageUpload',
            fields=[
                ('uploadmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.UploadModel')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Location')),
            ],
            bases=('base.uploadmodel',),
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_priority', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('case_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Status')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Status')),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Type')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Link')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseAuthorisation', verbose_name='Case Authorisation'),
        ),
        migrations.AddField(
            model_name='case',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseClassification', verbose_name='Case Classification'),
        ),
        migrations.AddField(
            model_name='case',
            name='image_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseImageUpload', verbose_name='Case Image Upload'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CasePriority', verbose_name='Case Priority'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseStatus', verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseType', verbose_name='Case Type'),
        ),
    ]
