# Generated by Django 2.0.3 on 2018-06-24 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('purpose', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Purpose')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Case Slug')),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='', verbose_name='Case Image')),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Deadline')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='case_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Authorisation')),
            ],
            options={
                'verbose_name': 'Case Classification',
                'verbose_name_plural': 'Case Classifications',
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Case Category',
                'verbose_name_plural': 'Case Categories',
            },
        ),
        migrations.CreateModel(
            name='CaseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Case Classification',
                'verbose_name_plural': 'Case Classifications',
            },
        ),
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason for Association')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Case', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Case Contact',
                'verbose_name_plural': 'Case Contacts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('entry', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Log Entry')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Note Title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Note Slug')),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='', verbose_name='Note Image')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Deadline')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='note_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('authorisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteAuthorisation', verbose_name='Note Authorisation')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteCategory', verbose_name='Note Category')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteClassification', verbose_name='Note Classification')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_manager', to=settings.AUTH_USER_MODEL, verbose_name='Note Manager')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NotePriority', verbose_name='Note Priority')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteStatus', verbose_name='Note Status')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteType', verbose_name='Note Type')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Case Priority',
                'verbose_name_plural': 'Case Priorities',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Case Status',
                'verbose_name_plural': 'Case Status',
            },
        ),
        migrations.CreateModel(
            name='CaseStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Status Group')),
                ('status', models.ManyToManyField(blank=True, to='case.CaseStatus', verbose_name='Case Status')),
            ],
            options={
                'verbose_name': 'Case Status Group',
                'verbose_name_plural': 'Case Status Groups',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('purpose', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Purpose')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Case Slug')),
                ('image_upload', models.TextField(blank=True, max_length=100, null=True, verbose_name='Case Image')),
                ('date_added', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date Added')),
                ('deadline', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deadline')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('authorisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseAuthorisation')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseCategory')),
                ('classification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseClassification')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CasePriority')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseStatus')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseType')),
            ],
            options={
                'verbose_name': 'historical Case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='LinkedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Link')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('case', models.ManyToManyField(blank=True, to='case.Case', verbose_name='Case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='the')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseAuthorisation', verbose_name='Case Authorisation'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseCategory', verbose_name='Case Category'),
        ),
        migrations.AddField(
            model_name='case',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseClassification', verbose_name='Case Classification'),
        ),
        migrations.AddField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_manager', to=settings.AUTH_USER_MODEL, verbose_name='Case Manager'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CasePriority', verbose_name='Case Priority'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseStatus', verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseType', verbose_name='Case Type'),
        ),
    ]
