# Generated by Django 2.0.3 on 2018-05-20 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('note', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('deadline', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Case Deadline')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Case Slug')),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='', verbose_name='Case Image')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseAuthorisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Classification')),
            ],
            options={
                'verbose_name': 'Case Classification',
                'verbose_name_plural': 'Case Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseClassificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Classification')),
            ],
            options={
                'verbose_name': 'Case Classification',
                'verbose_name_plural': 'Case Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.Note')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
            ],
            options={
                'abstract': False,
            },
            bases=('note.note',),
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Case Priority',
                'verbose_name_plural': 'Case Priorities',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Status Group')),
            ],
            options={
                'verbose_name': 'Case Status Group',
                'verbose_name_plural': 'Case Status Groups',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Status Type')),
            ],
            options={
                'verbose_name': 'Case Status Type',
                'verbose_name_plural': 'Case Status Types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Type')),
            ],
            options={
                'verbose_name': 'Case Type',
                'verbose_name_plural': 'Case Types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Reference')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Location')),
                ('brief', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Brief')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('deadline', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Case Deadline')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Case Slug')),
                ('image_upload', models.TextField(blank=True, max_length=100, null=True, verbose_name='Case Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('authorisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseAuthorisationType')),
                ('case_manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseClassificationType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CasePriority')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseStatusType')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseType')),
            ],
            options={
                'verbose_name': 'historical Case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='LinkedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Link')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('case', models.ManyToManyField(blank=True, to='case.Case', verbose_name='Case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='the')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestatusgroup',
            name='case_status',
            field=models.ManyToManyField(blank=True, to='case.CaseStatusType', verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseAuthorisationType', verbose_name='Case Authorisation'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_manager', to=settings.AUTH_USER_MODEL, verbose_name='Case Manager'),
        ),
        migrations.AddField(
            model_name='case',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseClassificationType', verbose_name='Case Classification'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CasePriority', verbose_name='Case Priority'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseStatusType', verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseType', verbose_name='Case Type'),
        ),
    ]
