# Generated by Django 2.0.3 on 2018-05-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason for Association')),
            ],
            options={
                'verbose_name': 'Case Contact',
                'verbose_name_plural': 'Case Contacts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('entry', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Log Entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='purpose',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Purpose'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='purpose',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Purpose'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case'),
        ),
        migrations.AddField(
            model_name='casecontact',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Case', verbose_name='Case'),
        ),
    ]
