# Generated by Django 2.0.3 on 2018-05-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Status Group')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Status Type')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='casestatus',
            name='case_status',
        ),
        migrations.AddField(
            model_name='casestatusgroup',
            name='case_status',
            field=models.ManyToManyField(blank=True, null=True, to='case.CaseStatusType', verbose_name='Case Status'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='cases_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseStatusType', verbose_name='Case Status'),
        ),
    ]
