# Generated by Django 2.0.3 on 2018-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20180520_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
    ]
