# Generated by Django 2.0.3 on 2018-05-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20180526_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created',
        ),
        migrations.RemoveField(
            model_name='case',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='modified',
        ),
    ]
