# Generated by Django 2.0.3 on 2018-05-26 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20180526_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
    ]
