# Generated by Django 2.0.3 on 2018-05-13 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0004_auto_20180513_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('id',), 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelManagers(
            name='case',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Case Slug'),
        ),
        migrations.AlterField(
            model_name='case',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Case Deadline'),
        ),
    ]
