# Generated by Django 2.0.3 on 2018-05-13 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0005_auto_20180513_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAuthorisationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Classification')),
            ],
            options={
                'verbose_name': 'Case Classification',
                'verbose_name_plural': 'Case Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='caseauthorisation',
            options={'ordering': ('id',), 'verbose_name': 'Case Authorisation', 'verbose_name_plural': 'Case Authorisations'},
        ),
        migrations.AlterModelOptions(
            name='caseclassification',
            options={'ordering': ('id',), 'verbose_name': 'Case Classification', 'verbose_name_plural': 'Case Classifications'},
        ),
        migrations.AlterModelOptions(
            name='casehistory',
            options={'ordering': ('id',), 'verbose_name': 'Case History', 'verbose_name_plural': 'Case Histories'},
        ),
        migrations.AlterModelOptions(
            name='caseimageupload',
            options={'ordering': ('id',), 'verbose_name': 'Case Image Upload', 'verbose_name_plural': 'Case Image Uploads'},
        ),
        migrations.AlterModelOptions(
            name='casepriority',
            options={'ordering': ('id',), 'verbose_name': 'Case Priority', 'verbose_name_plural': 'Case Priorities'},
        ),
        migrations.AlterModelOptions(
            name='casestatus',
            options={'ordering': ('id',), 'verbose_name': 'Case Status', 'verbose_name_plural': 'Case Status'},
        ),
        migrations.AlterModelOptions(
            name='casestatusgroup',
            options={'ordering': ('id',), 'verbose_name': 'Case Status Group', 'verbose_name_plural': 'Case Status Groups'},
        ),
        migrations.AlterModelOptions(
            name='casestatustype',
            options={'ordering': ('id',), 'verbose_name': 'Case Status Type', 'verbose_name_plural': 'Case Status Types'},
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={'ordering': ('id',), 'verbose_name': 'Case Type', 'verbose_name_plural': 'Case Types'},
        ),
        migrations.RenameField(
            model_name='caseclassification',
            old_name='cases_classification',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='casepriority',
            old_name='case_priority',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='casestatus',
            old_name='case_status',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='casetype',
            old_name='case_type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='caseauthorisation',
            name='case_authorisation',
        ),
        migrations.AddField(
            model_name='caseauthorisation',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Authorised By'),
        ),
        migrations.AddField(
            model_name='caseclassification',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='caseimageupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='casepriority',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='casetype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='linkedcase',
            name='linked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='the'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='case_status',
            field=models.ManyToManyField(blank=True, to='case.CaseStatusType', verbose_name='Case Status'),
        ),
        migrations.RemoveField(
            model_name='linkedcase',
            name='case',
        ),
        migrations.AddField(
            model_name='linkedcase',
            name='case',
            field=models.ManyToManyField(blank=True, to='case.Case', verbose_name='Case'),
        ),
        migrations.AddField(
            model_name='caseauthorisation',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseAuthorisationTypes', verbose_name='Case Authorisation'),
        ),
    ]
