# Generated by Django 2.0.3 on 2018-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20180526_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created',
        ),
        migrations.RemoveField(
            model_name='case',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='modified',
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Description'),
        ),
    ]
