# Generated by Django 2.0.3 on 2018-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20180526_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
    ]
