# Generated by Django 2.0.3 on 2018-05-26 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20180526_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
    ]
