# Generated by Django 2.0.3 on 2018-05-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20180526_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Category')),
            ],
            options={
                'verbose_name': 'Case Category',
                'verbose_name_plural': 'Case Categories',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='casecontact',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='linkedcase',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='case_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseCategory', verbose_name='Case Category'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.CaseCategory'),
        ),
    ]
