# Generated by Django 2.0.3 on 2018-05-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Case Note Type')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Case NoteSlug')),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='', verbose_name='Case Note Image')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ('id',),
            },
        ),
    ]
