# Generated by Django 2.0.3 on 2018-04-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Title')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Location')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation Date')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_authorisation', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Authorisation Status')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Authorisation')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Category')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Title')),
                ('background', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Background')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Location')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation Date')),
                ('deadline', models.DateTimeField(auto_now=True, null=True, verbose_name='Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('task_note', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Note')),
                ('note_hash', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Note Hash')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_priority', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('task_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Status')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Status')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Type')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='EvidenceTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.Evidence', verbose_name='Evidence')),
            ],
            bases=('tasks.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskAuthorisation', verbose_name='Task Authorisation'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskCategory', verbose_name='Task Category'),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskNotes', verbose_name='Task Notes'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskPriority', verbose_name='Task Priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskStatus', verbose_name='Task Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskType', verbose_name='Task Type'),
        ),
    ]
