# Generated by Django 2.0.3 on 2018-05-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAuthorisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Classification')),
            ],
            options={
                'verbose_name': 'Task Classification',
                'verbose_name_plural': 'Task Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskClassificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Classification')),
            ],
            options={
                'verbose_name': 'Task Classification',
                'verbose_name_plural': 'Task Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Status Group')),
            ],
            options={
                'verbose_name': 'Task Status Group',
                'verbose_name_plural': 'Task Status Groups',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Task Status Type')),
            ],
            options={
                'verbose_name': 'Task Status Type',
                'verbose_name_plural': 'Task Status Types',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ('id',), 'verbose_name': 'Task Category', 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'ordering': ('id',), 'verbose_name': 'Task Priority', 'verbose_name_plural': 'Task Priorities'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ('id',), 'verbose_name': 'Task Type', 'verbose_name_plural': 'Task Types'},
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='task_category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='taskpriority',
            old_name='task_priority',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tasktype',
            old_name='task_type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='task_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager', to=settings.AUTH_USER_MODEL, verbose_name='Case Manager'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskAuthorisationType', verbose_name='Task Authorisation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskStatusType', verbose_name='Task Status'),
        ),
        migrations.DeleteModel(
            name='TaskAuthorisation',
        ),
        migrations.DeleteModel(
            name='TaskNotes',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AddField(
            model_name='taskstatusgroup',
            name='Task_status',
            field=models.ManyToManyField(blank=True, to='tasks.TaskStatusType', verbose_name='Task Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TaskClassificationType', verbose_name='Task Classification'),
        ),
    ]
