# Generated by Django 2.0.3 on 2018-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('file_note', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_hash', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('upload_location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
