# Generated by Django 2.0.3 on 2018-05-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('date_recorded', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Recorded')),
                ('date_of_custody', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of Custody')),
                ('check_in', models.BooleanField(default=False, verbose_name='Checked-In')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('custody_receipt', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Custody Receipt Number')),
                ('custody_receipt_label', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Custody Receipt Label')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chainofcustody_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='chainofcustody_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chainofcustody_custodian', to=settings.AUTH_USER_MODEL, verbose_name='Custodian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Reference')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('evidence_bag_number', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Bag Number')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Physical Location')),
                ('uri', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='File Location')),
                ('current_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current Status')),
                ('qr_code_text', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='QR Code Text')),
                ('qr_code', models.BooleanField(default=False, verbose_name='QR Code')),
                ('retention_reminder_sent', models.BooleanField(default=False, verbose_name='Retention Reminder')),
                ('retention_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Date')),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('retention_start_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Start Date')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='evidence_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceAuthorisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Classification')),
            ],
            options={
                'verbose_name': 'Evidence Classification',
                'verbose_name_plural': 'Evidence Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Category')),
            ],
            options={
                'verbose_name': 'Evidence Category',
                'verbose_name_plural': 'Evidence Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceClassificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Classification')),
            ],
            options={
                'verbose_name': 'Evidence Classification',
                'verbose_name_plural': 'Evidence Classifications',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidencePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Evidence Priority',
                'verbose_name_plural': 'Evidence Priorities',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Status Group')),
            ],
            options={
                'verbose_name': 'Evidence Status Group',
                'verbose_name_plural': 'Evidence Status Groups',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Status Type')),
            ],
            options={
                'verbose_name': 'Evidence Status Type',
                'verbose_name_plural': 'Evidence Status Types',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Type')),
            ],
            options={
                'verbose_name': 'Evidence Type',
                'verbose_name_plural': 'Evidence Types',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='evidencestatusgroup',
            name='Evidence_status',
            field=models.ManyToManyField(blank=True, to='evidence.EvidenceStatusType', verbose_name='Evidence Status'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='authorisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceAuthorisationType', verbose_name='Evidence Authorisation'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceCategory', verbose_name='Evidence Category'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='chain_of_custody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_chain_of_custody', to='evidence.ChainOfCustody', verbose_name='Chain Of Custody'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceClassificationType', verbose_name='Evidence Classification'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_custodian', to=settings.AUTH_USER_MODEL, verbose_name='Custodian'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidencePriority', verbose_name='Evidence Priority'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceStatusType', verbose_name='Evidence Status'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceType', verbose_name='Evidence Type'),
        ),
    ]
