# Generated by Django 2.0.3 on 2018-04-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Recorded')),
                ('date_of_custody', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of Custody')),
                ('check_in', models.BooleanField(default=False, verbose_name='Checked-In')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('custody_receipt', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Custody Receipt Number')),
                ('custody_receipt_label', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Custody Receipt Label')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Reference')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('evidence_bag_number', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Bag Number')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Physical Location')),
                ('uri', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='File Location')),
                ('current_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current Status')),
                ('qr_code_text', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='QR Code Text')),
                ('qr_code', models.BooleanField(default=False, verbose_name='QR Code')),
                ('retention_reminder_sent', models.BooleanField(default=False, verbose_name='Retention Reminder')),
                ('retention_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Date')),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('retention_start_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Start Date')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='Case')),
                ('chain_of_custody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.ChainOfCustody', verbose_name='Chain Of Custody')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Title')),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Reference')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
                ('evidence_bag_number', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Bag Number')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Physical Location')),
                ('uri', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='File Location')),
                ('current_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current Status')),
                ('qr_code_text', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='QR Code Text')),
                ('qr_code', models.BooleanField(default=False, verbose_name='QR Code')),
                ('retention_reminder_sent', models.BooleanField(default=False, verbose_name='Retention Reminder')),
                ('retention_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Date')),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Added')),
                ('retention_start_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Retention Start Date')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceImageUpload',
            fields=[
                ('uploadmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.UploadModel')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Location')),
            ],
            bases=('base.uploadmodel',),
        ),
        migrations.CreateModel(
            name='EvidenceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('evidence_status', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Status')),
                ('comment', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Evidence Type')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='image_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceImageUpload', verbose_name='Evidence Image Upload'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceStatus', verbose_name='Evidence Status'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceType', verbose_name='Evidence Type'),
        ),
    ]
